export { default as HeaderCont } from "./HeaderCont";
export { default as MainCont } from "./MainCont";
export { default as Contents } from "./Contents";
export { default as Aside } from "./Aside";
export { default as ContentSlide } from "./ContentSlide";
export { default as ContentDesc } from "./ContentDesc";
export { default as Loader } from "./Loader";
export { default as AsideMain } from "./AsideMain";
export { default as AsideGlobal } from "./AsideGlobal";
